apiVersion: v1
kind: Service
metadata:
  name: poll-service
  namespace: default
  labels:
    app: poll
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 30
      targetPort: 30
  selector:
    app: poll