apiVersion: v1
kind: Service
metadata:
  name: traefik-service
  namespace: kube-public
  labels:
    app: traefik
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 30
      targetPort: 30
      nodePort: 30021
    - name: admin
      protocol: TCP
      port: 3030
      targetPort: 3030
      nodePort: 30042
  selector:
    app: traefik